//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIFreshOrder.JIFreshService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInfomation", Namespace="http://schemas.datacontract.org/2004/07/JIFreshController")]
    [System.SerializableAttribute()]
    public partial class ReturnInfomation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JIFreshService.IJIFresherControl")]
    public interface IJIFresherControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJIFresherControl/Login", ReplyAction="http://tempuri.org/IJIFresherControl/LoginResponse")]
        JIFreshOrder.JIFreshService.ReturnInfomation Login(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJIFresherControl/SubmitOrder", ReplyAction="http://tempuri.org/IJIFresherControl/SubmitOrderResponse")]
        JIFreshOrder.JIFreshService.ReturnInfomation SubmitOrder(string orderlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJIFresherControl/AlterOrder", ReplyAction="http://tempuri.org/IJIFresherControl/AlterOrderResponse")]
        JIFreshOrder.JIFreshService.ReturnInfomation AlterOrder(string OrderID, string orderlist);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJIFresherControlChannel : JIFreshOrder.JIFreshService.IJIFresherControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JIFresherControlClient : System.ServiceModel.ClientBase<JIFreshOrder.JIFreshService.IJIFresherControl>, JIFreshOrder.JIFreshService.IJIFresherControl {
        
        public JIFresherControlClient() {
        }
        
        public JIFresherControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JIFresherControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JIFresherControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JIFresherControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JIFreshOrder.JIFreshService.ReturnInfomation Login(string UserName, string Password) {
            return base.Channel.Login(UserName, Password);
        }
        
        public JIFreshOrder.JIFreshService.ReturnInfomation SubmitOrder(string orderlist) {
            return base.Channel.SubmitOrder(orderlist);
        }
        
        public JIFreshOrder.JIFreshService.ReturnInfomation AlterOrder(string OrderID, string orderlist) {
            return base.Channel.AlterOrder(OrderID, orderlist);
        }
    }
}
